# Generated by Django 5.2 on 2025-07-19 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Lease commencement date.')),
                ('deposit_amount', models.DecimalField(decimal_places=2, help_text='Security deposit held for the lease.', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether the lease is currently active.')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(db_index=True, help_text='Date invoice was generated or issued.')),
                ('due_date', models.DateField(db_index=True, help_text='Date by which payment is due.')),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Rent portion of the invoice.', max_digits=10)),
                ('water_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Water portion based on meter readings or shared policy.', max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Any additional fees or fines.', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Sum of rent, water, and other charges.', max_digits=10)),
                ('is_paid', models.BooleanField(db_index=True, default=False, help_text='Indicates if invoice is fully paid.')),
                ('auto_generated', models.BooleanField(default=True, help_text='Marks invoices created automatically by system vs manual.')),
                ('lease', models.ForeignKey(help_text='Lease this invoice is billed against.', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenant_management.lease')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid.', max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when payment was recorded.')),
                ('method', models.CharField(default='Mpesa', help_text='Payment method used.', max_length=50)),
                ('mpesa_receipt', models.CharField(blank=True, help_text='Reference code from M-Pesa.', max_length=100, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining invoice balance after this payment.', max_digits=10)),
                ('invoice', models.ForeignKey(help_text='Invoice this payment applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant_management.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The display name of the property.', max_length=100)),
                ('location', models.CharField(help_text='Physical address or description of the property location.', max_length=255)),
                ('water_policy', models.CharField(choices=[('shared', 'Shared'), ('meter', 'Per Meter'), ('prepaid', 'Prepaid')], db_index=True, default='shared', help_text='Defines how water billing is handled: shared, metered, or prepaid.', max_length=50)),
                ('water_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per cubic meter of water for metered properties (Ksh).', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the property record was created.')),
            ],
            options={
                'indexes': [models.Index(fields=['water_policy'], name='tenant_mana_water_p_697985_idx')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Unique identifier for this receipt.', max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when receipt was created.')),
                ('payment', models.OneToOneField(help_text='The payment this receipt is issued for.', on_delete=django.db.models.deletion.CASCADE, to='tenant_management.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Tenant's full legal name.", max_length=100)),
                ('phone_number', models.CharField(help_text="Tenant's primary contact phone number.", max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Optional email for notifications and records.', max_length=254, null=True)),
                ('national_id', models.CharField(help_text='Official government-issued identification number.', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the tenant record was created.')),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number'], name='tenant_mana_phone_n_db59ee_idx'), models.Index(fields=['national_id'], name='tenant_mana_nationa_6b1c25_idx')],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant making the payment.', on_delete=django.db.models.deletion.CASCADE, to='tenant_management.tenant'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Content of the sent notification.')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], help_text='Delivery channel used for this notification.', max_length=10)),
                ('status', models.CharField(default='sent', help_text='Delivery status (sent, failed).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was logged.')),
                ('tenant', models.ForeignKey(help_text='Recipient tenant of the notification.', on_delete=django.db.models.deletion.CASCADE, to='tenant_management.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant taking the lease.', on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenant_management.tenant'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='Identifier for the unit within the property (e.g., A1, B12).', max_length=50)),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Monthly rent amount for this unit (Ksh).', max_digits=10)),
                ('is_occupied', models.BooleanField(db_index=True, default=False, help_text='Indicates whether the unit is currently occupied by a tenant.')),
                ('meter_number', models.CharField(blank=True, help_text='Identifier for the water meter, if this unit uses metered billing.', max_length=50, null=True)),
                ('property', models.ForeignKey(help_text='The parent property this unit belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='tenant_management.property')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(auto_now_add=True, db_index=True, help_text='Date when the meter was read.')),
                ('previous_reading', models.DecimalField(decimal_places=2, help_text='Last recorded meter value.', max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, help_text='New meter value entered by user.', max_digits=10)),
                ('usage', models.DecimalField(decimal_places=2, editable=False, help_text='Calculated usage in cubic meters.', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, help_text="Calculated cost for the usage at the unit's property rate.", max_digits=10)),
                ('unit', models.ForeignKey(help_text='Unit associated with this meter reading.', on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='tenant_management.unit')),
            ],
            options={
                'get_latest_by': 'reading_date',
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.OneToOneField(help_text='The specific unit leased by the tenant.', on_delete=django.db.models.deletion.CASCADE, to='tenant_management.unit'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['lease', 'invoice_date'], name='tenant_mana_lease_i_3a97a4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_paid'], name='tenant_mana_is_paid_70b6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='tenant_mana_receipt_021b43_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='tenant_mana_tenant__95e295_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['tenant', 'created_at'], name='tenant_mana_tenant__e1d299_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property', 'unit_number'], name='tenant_mana_propert_58a47c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'unit_number')},
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['unit', 'reading_date'], name='tenant_mana_unit_id_c71075_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['start_date'], name='tenant_mana_start_d_3bdbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['is_active'], name='tenant_mana_is_acti_2f1f1b_idx'),
        ),
    ]
