# Generated by Django 5.2 on 2025-08-28 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateField(help_text='Start date of billing period (e.g., 1st of the month).')),
                ('billing_period_end', models.DateField(help_text='End date of billing period (e.g., last day of the month).')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Sum of all invoice lines for this tenant.', max_digits=10)),
                ('is_paid', models.BooleanField(db_index=True, default=False, help_text='Indicates if the invoice is fully paid.')),
                ('auto_generated', models.BooleanField(default=True, help_text='Marks if invoice is generated automatically.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Lease commencement date.')),
                ('deposit_amount', models.DecimalField(decimal_places=2, help_text='Security deposit held for the lease.', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether the lease is currently active.')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The display name of the property.', max_length=100)),
                ('location', models.CharField(help_text='Physical address or description of the property location.', max_length=255)),
                ('water_policy', models.CharField(choices=[('shared', 'Shared'), ('meter', 'Per Meter'), ('prepaid', 'Prepaid')], db_index=True, default='shared', help_text='Defines how water billing is handled: shared, metered, or prepaid.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the property record was created.')),
            ],
        ),
        migrations.CreateModel(
            name='WaterCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Description of the charge (e.g., 'Rent', 'Water').", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this line item.', max_digits=10)),
                ('invoice', models.ForeignKey(help_text='Invoice this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_management.invoice')),
                ('lease', models.ForeignKey(blank=True, help_text='Lease this line corresponds to, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='tenant_management.lease')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid.', max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when payment was recorded.')),
                ('method', models.CharField(default='Mpesa', help_text='Payment method used.', max_length=50)),
                ('reference', models.CharField(blank=True, help_text='Payment reference or receipt number (from Mpesa or bank).', max_length=100, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining invoice balance after this payment.', max_digits=10)),
                ('invoice', models.ForeignKey(help_text='Invoice this payment applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant_management.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Unique identifier for this receipt.', max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when receipt was created.')),
                ('payment', models.OneToOneField(help_text='The payment this receipt is issued for.', on_delete=django.db.models.deletion.CASCADE, to='tenant_management.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Tenant's full legal name.", max_length=100)),
                ('phone_number', models.CharField(help_text="Tenant's primary contact phone number (unique per property).", max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Optional email for notifications and records.', max_length=254, null=True)),
                ('national_id', models.CharField(help_text='Official government-issued identification number.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='The property this tenant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenant_management.property')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Content of the sent notification.')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], help_text='Delivery channel used for this notification.', max_length=10)),
                ('status', models.CharField(default='sent', help_text='Delivery status (sent, failed).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was logged.')),
                ('tenant', models.ForeignKey(help_text='Recipient tenant of the notification.', on_delete=django.db.models.deletion.CASCADE, to='tenant_management.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant taking the lease.', on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant being billed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenant_management.tenant'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='Identifier for the unit within the property (e.g., A1, B12).', max_length=50)),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Monthly rent amount for this unit (Ksh).', max_digits=10)),
                ('is_occupied', models.BooleanField(db_index=True, default=False, help_text='Indicates whether the unit is currently occupied by a tenant.')),
                ('meter_number', models.CharField(blank=True, help_text='Identifier for the water meter, if this unit uses metered billing.', max_length=50, null=True)),
                ('property', models.ForeignKey(help_text='The parent property this unit belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='tenant_management.property')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(auto_now_add=True, db_index=True, help_text='Date when the meter was read.')),
                ('previous_reading', models.DecimalField(decimal_places=2, help_text='Last recorded meter value.', max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, help_text='New meter value entered by user.', max_digits=10)),
                ('usage', models.DecimalField(decimal_places=2, editable=False, help_text='Calculated usage in cubic meters.', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, help_text="Calculated cost for the usage at the unit's property rate.", max_digits=10)),
                ('unit', models.ForeignKey(help_text='Unit associated with this meter reading.', on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='tenant_management.unit')),
            ],
            options={
                'get_latest_by': 'reading_date',
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(help_text='The unit leased by the tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenant_management.unit'),
        ),
        migrations.AddField(
            model_name='property',
            name='water_company',
            field=models.ForeignKey(help_text='Water company supplying this property.', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='tenant_management.watercompany'),
        ),
        migrations.CreateModel(
            name='WaterRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_cubic_meter', models.DecimalField(decimal_places=2, help_text='Cost per cubic meter (unit) of water.', max_digits=10)),
                ('effective_from', models.DateField(help_text='Date from which this rate becomes effective.')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this rate is valid. Null = still active.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if this is the current active rate.')),
                ('water_company', models.ForeignKey(help_text='The water company this rate applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='water_rates', to='tenant_management.watercompany')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_date'], name='tenant_mana_invoice_33abe6_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='tenant_mana_receipt_021b43_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['property', 'phone_number'], name='tenant_mana_propert_77ecb2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['property', 'national_id'], name='tenant_mana_propert_820429_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('property', 'phone_number'), name='unique_tenant_phone_per_property'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('property', 'national_id'), name='unique_tenant_id_per_property'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['tenant', 'created_at'], name='tenant_mana_tenant__e1d299_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'billing_period_start'], name='tenant_mana_tenant__798ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_paid'], name='tenant_mana_is_paid_70b6c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenant', 'billing_period_start', 'billing_period_end')},
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property', 'unit_number'], name='tenant_mana_propert_58a47c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'unit_number')},
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['unit', 'reading_date'], name='tenant_mana_unit_id_c71075_idx'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('unit',), name='unique_active_lease_per_unit'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['water_policy'], name='tenant_mana_water_p_697985_idx'),
        ),
        migrations.AddIndex(
            model_name='waterrate',
            index=models.Index(fields=['water_company', 'is_active'], name='tenant_mana_water_c_7fbb6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='waterrate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('water_company',), name='unique_active_rate_per_company'),
        ),
        migrations.AlterUniqueTogether(
            name='waterrate',
            unique_together={('water_company', 'effective_from')},
        ),
    ]
