# Generated by Django 5.2 on 2025-11-20 15:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Readings'), ('FINALIZED', 'Finalized')], db_index=True, default='DRAFT', max_length=32)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('auto_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usage', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('rate_per_cubic_meter', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
            ],
            options={
                'get_latest_by': 'reading_date',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('water_policy', models.CharField(choices=[('shared', 'Shared'), ('meter', 'Per Meter'), ('prepaid', 'Prepaid')], db_index=True, default='shared', max_length=50)),
                ('billing_day', models.PositiveSmallIntegerField(default=1, help_text='Day of the month when rent invoices are generated (e.g., 5 = 5th of each month).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_held', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='tenant_management.lease')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('RENT', 'Rent'), ('WATER', 'Water'), ('DEPOSIT', 'DepositApplied'), ('REFUND', 'Refund'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_lines', to='tenant_management.deposit')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_management.invoice')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='tenant_management.lease')),
                ('meter_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='tenant_management.meterreading')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('national_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenant_management.property')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(default='Mpesa', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(choices=[('RENT', 'Rent Payment'), ('DEPOSIT', 'Deposit Payment'), ('MIXED', 'Mixed Payment'), ('CREDIT', 'Credit Application')], default='MIXED', max_length=20)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant_management.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant_management.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=10)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_management.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('rent', 'Rent')], default='deposit', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_management.deposit')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_management.invoice')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_management.lease')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_management.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='tenant_management.tenant'),
        ),
        migrations.CreateModel(
            name='TenantBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='tenant_management.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_occupied', models.BooleanField(db_index=True, default=False)),
                ('meter_number', models.CharField(blank=True, max_length=50, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='tenant_management.property')),
            ],
        ),
        migrations.AddField(
            model_name='meterreading',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='tenant_management.unit'),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenant_management.unit'),
        ),
        migrations.AddField(
            model_name='property',
            name='water_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='tenant_management.watercompany'),
        ),
        migrations.CreateModel(
            name='WaterRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_cubic_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('water_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_rates', to='tenant_management.watercompany')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenant_management.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['receipt_number'], name='tenant_mana_receipt_021b43_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['property', 'phone_number'], name='tenant_mana_propert_77ecb2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['property', 'national_id'], name='tenant_mana_propert_820429_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('property', 'phone_number'), name='unique_tenant_phone_per_property'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('property', 'national_id'), name='unique_tenant_id_per_property'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='tenant_mana_tenant__95e295_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='tenant_mana_payment_5d8c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_date'], name='tenant_mana_invoice_33abe6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['tenant', 'created_at'], name='tenant_mana_tenant__e1d299_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='tenant_mana_tenant__1e1bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['billing_period_start'], name='tenant_mana_billing_3282d7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['billing_period_end'], name='tenant_mana_billing_3ca3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'is_paid'], name='tenant_mana_tenant__ff2aa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenant', 'billing_period_start', 'billing_period_end')},
        ),
        migrations.AddIndex(
            model_name='tenantbalance',
            index=models.Index(fields=['tenant'], name='tenant_mana_tenant__869dde_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbalance',
            index=models.Index(fields=['balance'], name='tenant_mana_balance_236df5_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property', 'unit_number'], name='tenant_mana_propert_58a47c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'unit_number')},
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['unit', 'reading_date'], name='tenant_mana_unit_id_c71075_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['current_reading'], name='tenant_mana_current_14c5c5_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['is_active'], name='tenant_mana_is_acti_2f1f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_mana_tenant__7bbd1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('unit',), name='unique_active_lease_per_unit'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['water_policy'], name='tenant_mana_water_p_697985_idx'),
        ),
        migrations.AddIndex(
            model_name='waterrate',
            index=models.Index(fields=['water_company', 'is_active'], name='tenant_mana_water_c_7fbb6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='waterrate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('water_company',), name='unique_active_rate_per_company'),
        ),
        migrations.AlterUniqueTogether(
            name='waterrate',
            unique_together={('water_company', 'effective_from')},
        ),
    ]
