# Generated by Django 5.2 on 2025-08-29 10:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_held', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('rent', 'Rent')], default='deposit', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('RENT', 'Rent'), ('WATER', 'Water'), ('DEPOSIT', 'DepositApplied'), ('REFUND', 'Refund'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='meter_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='tenant_management.meterreading'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='auto_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_period_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_period_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenant_management.tenant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_management.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='tenant_management.lease'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lease',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenant_management.tenant'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenant_management.unit'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='current_reading',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='previous_reading',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='reading_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='tenant_management.unit'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='usage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_management.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant_management.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='Mpesa', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='water_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='tenant_management.watercompany'),
        ),
        migrations.AlterField(
            model_name='property',
            name='water_policy',
            field=models.CharField(choices=[('shared', 'Shared'), ('meter', 'Per Meter'), ('prepaid', 'Prepaid')], db_index=True, default='shared', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenant_management.payment'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='national_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenant_management.property'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_occupied',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='meter_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='tenant_management.property'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterrate',
            name='effective_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='waterrate',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterrate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='waterrate',
            name='rate_per_cubic_meter',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='waterrate',
            name='water_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_rates', to='tenant_management.watercompany'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['start_date'], name='tenant_mana_start_d_3bdbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['is_active'], name='tenant_mana_is_acti_2f1f1b_idx'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='tenant_management.lease'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_management.payment'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_lines', to='tenant_management.deposit'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_management.deposit'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_management.invoice'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_management.lease'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_management.tenant'),
        ),
    ]
