# Generated by Django 5.2 on 2025-11-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
