# Generated by Django 5.2 on 2025-08-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenant_mana_phone_n_db59ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenant_mana_nationa_6b1c25_idx',
        ),
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(default=11, help_text='The property this tenant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenant_management.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='national_id',
            field=models.CharField(help_text='Official government-issued identification number.', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(help_text="Tenant's primary contact phone number (unique per property).", max_length=15),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['property', 'phone_number'], name='tenant_mana_propert_77ecb2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['property', 'national_id'], name='tenant_mana_propert_820429_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('property', 'phone_number'), name='unique_tenant_phone_per_property'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('property', 'national_id'), name='unique_tenant_id_per_property'),
        ),
    ]
