# Generated by Django 5.2 on 2025-12-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_lease_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='previous_reading_date',
            field=models.DateField(blank=True, help_text='The date the previous reading was taken', null=True),
        ),
    ]
