# Generated by Django 5.2 on 2025-08-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_deposit_ledgerentry_invoiceline_line_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='payment',
        ),
    ]
