# Generated by Django 5.2 on 2025-12-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0003_meterreading_previous_reading_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='tenant_mana_billing_3ca3f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='tenant_mana_tenant__ff2aa9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenant_management.lease'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['lease'], name='tenant_mana_lease_i_308716_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('lease', 'billing_period_start', 'billing_period_end'), name='unique_invoice_per_lease_period'),
        ),
    ]
