# Generated by Django 5.2 on 2025-08-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0003_remove_deposit_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='current_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
