# Generated by Django 5.2 on 2025-12-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0004_remove_invoice_tenant_mana_billing_3ca3f3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='billing_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of month for rent generation.'),
        ),
    ]
