# Generated by Django 5.2 on 2025-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0004_alter_meterreading_current_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Readings'), ('FINALIZED', 'Finalized')], db_index=True, default='DRAFT', max_length=32),
        ),
        migrations.AddField(
            model_name='property',
            name='billing_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of the month when rent invoices are generated (e.g., 5 = 5th of each month).'),
        ),
    ]
