# Generated by Django 5.2 on 2025-08-30 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0005_invoice_status_property_billing_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='reading_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
