# Generated by Django 5.2 on 2025-12-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0005_alter_property_billing_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
