# Generated by Django 5.2 on 2025-09-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0006_alter_meterreading_reading_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='usage',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
