# Generated by Django 5.2 on 2025-09-02 10:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0007_alter_meterreading_amount_alter_meterreading_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='tenant_management.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='tenant_mana_tenant__869dde_idx')],
            },
        ),
    ]
