# Generated by Django 5.2 on 2025-09-02 10:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0008_tenantbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount_held',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
