# Generated by Django 5.2 on 2025-09-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0009_alter_deposit_amount_held_alter_deposit_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='rate_per_cubic_meter',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
