# Generated by Django 5.2 on 2025-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0013_alter_payment_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance_after',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('RENT', 'Rent Payment'), ('DEPOSIT', 'Deposit Payment'), ('MIXED', 'Mixed Payment'), ('CREDIT', 'Credit Application')], default='MIXED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='tenant_mana_tenant__95e295_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='tenant_mana_payment_5d8c5c_idx'),
        ),
    ]
