# Generated by Django 5.2 on 2025-10-04 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_journalentry_is_reversal_journalentry_reversal_of'),
        ('easydocs', '0007_payment_received_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='reversal_of',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='client_service',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='client_sub_service',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='legal_payout',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='payment',
        ),
        migrations.CreateModel(
            name='CashbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('IN', 'Cash In'), ('OUT', 'Cash Out')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who recorded this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_payment', models.ForeignKey(blank=True, help_text='Link to client payment if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='easydocs.payment')),
                ('related_service', models.ForeignKey(blank=True, help_text='Link to client service if payout related', null=True, on_delete=django.db.models.deletion.SET_NULL, to='easydocs.clientservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CashReserve',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='LedgerAccount',
        ),
        migrations.DeleteModel(
            name='JournalLine',
        ),
    ]
