# Generated by Django 5.2 on 2025-10-04 19:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_journalentry_created_by_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbookentry',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.RemoveField(
            model_name='cashbookentry',
            name='related_payment',
        ),
        migrations.RemoveField(
            model_name='cashbookentry',
            name='related_service',
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
