# Generated by Django 5.2 on 2025-10-04 21:19

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cashbookentry_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='cashbookentry',
            index=models.Index(fields=['created_at'], name='accounts_ca_created_707d86_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbookentry',
            index=models.Index(fields=['entry_type'], name='accounts_ca_entry_t_79ca33_idx'),
        ),
    ]
