# Generated by Django 5.2 on 2025-10-05 11:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_cashbookentry_created_at_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='entry_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='cashbookentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_opening_balance', True)), fields=('entry_date',), name='unique_opening_balance_date'),
        ),
    ]
