#version: '3.9'

services:
  web:
    build: .
    entrypoint: ["/app/entrypoint.sh"]
    command: gunicorn GGI.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
      - ./staticfiles:/app/static_files
      - ./media:/app/media  # Bind mount media folder
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RUN_MIGRATIONS: "true"
      WAIT_FOR_REDIS: "true"
      RUN_COLLECT_STATIC: "true"
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-easydocs}
      POSTGRES_USER: ${POSTGRES_USER:-easydocsuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-easydocsuser} -d ${POSTGRES_DB:-easydocs}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery-worker:
    build: .
    command: celery -A GGI worker --loglevel=info
    volumes:
      - .:/app
      - ./media:/app/media  # Bind mount media folder
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started
    environment:
      RUN_MIGRATIONS: "false"
      WAIT_FOR_REDIS: "true"
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

  celery-beat:
    build: .
    entrypoint: ["/app/entrypoint.sh"]
    command: celery -A GGI beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
      - ./media:/app/media  # Bind mount media folder
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started
    environment:
      RUN_MIGRATIONS: "false"
      WAIT_FOR_REDIS: "true"
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media  # Bind mount media folder
    depends_on:
      - web

  flower:
    image: mher/flower
    command: >
      celery --broker=redis://redis:6379/0 flower
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  static_volume: