# Generated by Django 5.2 on 2026-03-27 15:28

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(db_index=True, help_text="Official company/organization name (e.g., 'GGI Surveys', 'Water Fiti')", max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier derived from name', max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If False, tenant is suspended (data preserved, access denied)')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the tenant account was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Last time tenant configuration was modified')),
                ('plan', models.CharField(choices=[('starter', 'Starter - Basic Features'), ('professional', 'Professional - Advanced Features'), ('enterprise', 'Enterprise - Custom Solution')], default='starter', help_text='Current subscription tier', max_length=20)),
                ('paid_until', models.DateField(blank=True, help_text='Date when current subscription expires (None = unpaid/trial)', null=True)),
                ('trial_period_days', models.IntegerField(default=30, help_text='Number of trial days (30 days from creation)')),
                ('logo', models.ImageField(blank=True, help_text='Company branding logo', null=True, upload_to='company_logos/')),
                ('description', models.TextField(blank=True, help_text='Company description for admin/support purposes')),
                ('phone', models.CharField(blank=True, help_text='Main company phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Main company email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Company website URL')),
                ('admin_email', models.EmailField(help_text='Email of primary tenant administrator (for billing/support notifications)', max_length=254)),
                ('admin_name', models.CharField(blank=True, help_text='Name of primary administrator', max_length=255)),
                ('max_users', models.IntegerField(default=10, help_text='Maximum number of users allowed (based on plan)')),
                ('max_clients', models.IntegerField(default=100, help_text='Maximum number of clients (based on plan)')),
                ('max_storage_gb', models.IntegerField(default=10, help_text='Maximum storage in GB (based on plan)')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier for this tenant', unique=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (for support/admin purposes)')),
            ],
            options={
                'verbose_name': 'Company (Tenant)',
                'verbose_name_plural': 'Companies (Tenants)',
                'ordering': ['created_on'],
                'indexes': [models.Index(fields=['is_active', 'created_on'], name='tenants_com_is_acti_b10370_idx'), models.Index(fields=['plan'], name='tenants_com_plan_f562bc_idx'), models.Index(fields=['slug'], name='tenants_com_slug_a29b26_idx')],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text="Full domain name (e.g., 'ggi.plotsync.local', 'surveyor.ggi.com')", max_length=253, unique=True, validators=[django.core.validators.URLValidator()])),
                ('is_primary', models.BooleanField(default=False, help_text='If True, this is the default domain for the tenant')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this domain was added')),
                ('tenant', models.ForeignKey(help_text='The company/tenant this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['is_primary', '-created_on'],
                'indexes': [models.Index(fields=['tenant', 'is_primary'], name='tenants_dom_tenant__3bd559_idx'), models.Index(fields=['domain'], name='tenants_dom_domain_6df599_idx')],
            },
        ),
    ]
