# Generated by Django 5.2 on 2026-03-27 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(db_index=True, help_text="Full domain name (e.g., 'ggi.plotsync.local', 'surveyor.ggi.com')", max_length=253, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain like tenant.plotsync.local (no http/https).', regex='^(?=.{1,253}$)(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$')]),
        ),
    ]
