# Generated by Django 5.2 on 2026-03-27 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_domain_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter - Basic Features'), ('professional', 'Professional - Advanced Features'), ('enterprise', 'Enterprise - Custom Solution')], help_text='Plan tier purchased', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=12)),
                ('months_purchased', models.PositiveIntegerField(default=1, help_text='Number of months this payment covers')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date the payment was received')),
                ('reference', models.CharField(blank=True, help_text='Payment reference number / transaction ID', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this payment')),
                ('recorded_by', models.CharField(blank=True, help_text='Username of platform admin who recorded this payment', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='The tenant company this payment was made for', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'payment_date'], name='tenants_sub_company_949f30_idx')],
            },
        ),
    ]
