# Generated by Django 5.2 on 2026-03-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when this tenant is soft-deleted (archived). NULL = not deleted.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='deleted_by',
            field=models.CharField(blank=True, help_text='Username of the platform admin who archived this tenant.', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Optional reason recorded at time of archiving.'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['deleted_at'], name='tenants_com_deleted_434b67_idx'),
        ),
    ]
