# Generated by Django 5.2 on 2025-05-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0008_alter_legalofficepayout_subservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='department',
            field=models.CharField(choices=[('Legal', 'Legal')], default='Legal', max_length=20),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
