# Generated by Django 5.2 on 2025-05-16 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0014_document_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='collected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
