# Generated by Django 5.2 on 2025-05-20 23:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0021_clientdoc_mime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('scheduled_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_preview', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='RecurringBroadcast',
        ),
    ]
