# Generated by Django 5.2 on 2026-01-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='push_notifications_allowed',
            field=models.BooleanField(default=False, help_text='True if the user has granted permission and has a valid FCM token.'),
        ),
    ]
