# Generated by Django 5.2 on 2025-05-06 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-pay_for_month']},
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='Employee.employeeprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'pay_for_month')},
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['pay_for_month'], name='Employee_pa_pay_for_06a3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['is_paid'], name='Employee_pa_is_paid_dcb4b6_idx'),
        ),
    ]
