# Generated by Django 5.2 on 2025-05-07 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_payroll_options_alter_payroll_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.RemoveField(
            model_name='allowance',
            name='payroll',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='payroll',
        ),
        # migrations.AlterModelOptions(
        #     name='payroll',
        #     options={'ordering': ['-month']},
        # ),
        migrations.RemoveIndex(
            model_name='payroll',
            name='Employee_pa_pay_for_06a3ec_idx',
        ),
        # migrations.AlterUniqueTogether(
        #     name='payroll',
        #     unique_together={('employee', 'month')},
        # ),
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),


        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.DateField(blank=True, help_text='First day of payroll month', null=True),
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-month']},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'month')},
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_allowances',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='allowancesnapshot',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_snapshots', to='Employee.payroll'),
        ),
        migrations.AddField(
            model_name='allowancetemplate',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_templates', to='Employee.employeeprofile'),
        ),
        migrations.AddField(
            model_name='allowancesnapshot',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.allowancetemplate'),
        ),
        migrations.AddField(
            model_name='deductionsnapshot',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_snapshots', to='Employee.payroll'),
        ),
        migrations.AddField(
            model_name='deductiontemplate',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_templates', to='Employee.employeeprofile'),
        ),
        migrations.AddField(
            model_name='deductionsnapshot',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.deductiontemplate'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='Employee.employeeprofile'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='Employee.employeesalary'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['month'], name='Employee_pa_month_a9d114_idx'),
        ),
        migrations.DeleteModel(
            name='Allowance',
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='pay_for_month',
        ),
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together={('employee', 'effective_from')},
        ),
    ]
