# Generated by Django 5.2 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employeeprofile_push_notifications_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('Surveyor', 'Surveyor'),
                    ('FrontOffice', 'Front Office'),
                    ('Admin', 'Admin'),
                    ('ITSupport', 'IT Support'),
                ],
                default='FrontOffice',
                max_length=20,
            ),
        ),
    ]
