# Generated by Django 5.2 on 2025-05-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_allowancesnapshot_allowancetemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.DateField(help_text='First day of payroll month'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='salary_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='Employee.employeesalary'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
