# Generated by Django 5.2 on 2025-05-16 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_payroll_month_alter_payroll_salary_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancesnapshot',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allowancesnapshot',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deductionsnapshot',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deductionsnapshot',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allowancesnapshot',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.allowancetemplate',null=True,
           blank=True),
        ),
        migrations.AlterField(
            model_name='deductionsnapshot',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.deductiontemplate',null=True,
          blank=True),
        ),
    ]
