# Generated by Django 5.2 on 2025-05-03 21:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter document type name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton_enforcer', models.BooleanField(default=True, editable=False, unique=True)),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_host_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('step_order', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_template', models.TextField()),
                ('scheduled_time', models.TimeField(help_text='Time of day to send the message (e.g. 10:00 AM)')),
                ('scheduled_day', models.PositiveSmallIntegerField(help_text='Day of the month to send (1–31)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this broadcast is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(choices=[('title', 'Title Deed Service'), ('ground', 'Ground Service')], default='title', max_length=20)),
                ('dispatch_message', models.TextField(blank=True, help_text='Message to send for dispatch-based services.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False, unique=True)),
                ('company_name', models.CharField(default='GREAT GUARDIAN', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('tagline', models.CharField(blank=True, default='Thank you for letting us serve you!', max_length=255)),
                ('stamp_signature', models.ImageField(blank=True, null=True, upload_to='company/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SmsProviderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=255)),
                ('sender_id', models.CharField(max_length=255)),
                ('singleton_enforcer', models.BooleanField(default=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_description', models.CharField(max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('collected', 'Title Deed Collected')], default='active', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='easydocs.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='easydocs.service')),
            ],
        ),
        migrations.CreateModel(
            name='ClientServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overridden_cost', models.DecimalField(blank=True, decimal_places=2, help_text='If set, this cost is used instead of the template cost', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('collected', 'Title Deed Collected')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_processes', to='easydocs.clientservice')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_processes', to='easydocs.process')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('overridden_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use default sub-service price', max_digits=10, null=True)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='easydocs.clientservice')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='easydocs.subservice')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_file', models.FileField(upload_to='client_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to='easydocs.client')),
                ('uploaded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_doc', to='easydocs.doctype')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], max_length=32)),
                ('receipt_no', models.CharField(blank=True, max_length=64)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('reason', models.CharField(max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('send_status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easydocs.client')),
                ('client_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='easydocs.clientservice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='easydocs.clientservice')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='easydocs.service'),
        ),
        migrations.CreateModel(
            name='TitleDeedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_by', models.CharField(help_text='Name of the person who picked the title deed', max_length=100)),
                ('id_number', models.CharField(blank=True, help_text='ID number of collector', max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_deed_collection', to='easydocs.clientservice')),
                ('submitted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(help_text='Enter a short name for the document', max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, help_text='Upload office-related documents', null=True, upload_to='office_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='easydocs.doctype')),
            ],
            options={
                'indexes': [models.Index(fields=['doc_name'], name='easydocs_do_doc_nam_916037_idx'), models.Index(fields=['location'], name='easydocs_do_locatio_fa8161_idx'), models.Index(fields=['uploaded_at'], name='easydocs_do_uploade_65a740_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('service_step', 'Service Process Step Payment'), ('sub_service', 'Sub-service Payment')], default='payment_step', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='easydocs.clientservice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='easydocs.payment')),
                ('service_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easydocs.clientserviceprocess')),
                ('sub_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easydocs.clientsubservice')),
            ],
            options={
                'indexes': [models.Index(fields=['reason'], name='easydocs_pa_reason_b74f2a_idx'), models.Index(fields=['created_at'], name='easydocs_pa_created_274ff3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(fields=('service', 'step_order'), name='unique_step_per_service_v2'),
        ),
        migrations.AddConstraint(
            model_name='clientservice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('client', 'service', 'land_description'), name='unique_active_service_per_land_v2'),
        ),
    ]
