# Generated by Django 5.2 on 2025-09-27 09:49

import apps.EasyDocs.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter document type name', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('step_order', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('scheduled_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_preview', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(choices=[('title', 'Title Deed Service'), ('ground', 'Ground Service')], default='title', max_length=20)),
                ('requires_title_collection', models.BooleanField(default=False, help_text='If true, after the final process we show Confirm & Collect buttons; otherwise just Complete')),
            ],
        ),
        migrations.CreateModel(
            name='SmsProviderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=255)),
                ('sender_id', models.CharField(max_length=255)),
                ('singleton_enforcer', models.BooleanField(default=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Legal', 'Legal')], default='Legal', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed'), ('drive_sync', 'Drive Sync'), ('drive_failed', 'Drive Sync Failed')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateTimeField()),
                ('dispatch_message', models.TextField(blank=True, null=True)),
                ('handled', models.BooleanField(default=False)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, help_text='Who marked this booking as handled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easydocs.booking')),
                ('surveyor', models.ForeignKey(limit_choices_to={'groups__name': 'Surveyor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assigned_at'],
                'unique_together': {('booking', 'surveyor')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='surveyors',
            field=models.ManyToManyField(help_text='Which surveyors were allocated', limit_choices_to={'groups__name': 'Surveyor'}, related_name='assigned_bookings', through='easydocs.BookingAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_description', models.CharField(max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overridden_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('full_total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Denormalized total for fast reads', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('collected', 'Title Deed Collected')], default='active', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='easydocs.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='easydocs.service')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='client_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='easydocs.clientservice'),
        ),
        migrations.CreateModel(
            name='ClientServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overridden_cost', models.DecimalField(blank=True, decimal_places=2, help_text='If set, this cost is used instead of the template cost', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('collected', 'Title Deed Collected')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_processes', to='easydocs.clientservice')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_processes', to='easydocs.process')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('overridden_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use default sub-service price', max_digits=10, null=True)),
                ('is_paid_to_legal_office', models.BooleanField(default=False)),
                ('paid_month', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('institution_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overridden_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='easydocs.clientservice')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='easydocs.subservice')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_file', models.FileField(storage='dynamic', upload_to='', validators=[apps.EasyDocs.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('storage_backend', models.CharField(choices=[('local', 'Local Storage'), ('drive', 'Google Drive'), ('hybrid', 'Both Local and Drive')], default='local', max_length=20)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_url', models.URLField(blank=True, null=True)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded to Drive'), ('local', 'Local Only'), ('failed', 'Upload Failed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='easydocs.client')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easydocs.doctype')),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_file', models.FileField(storage='dynamic', upload_to='', validators=[apps.EasyDocs.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('storage_backend', models.CharField(choices=[('local', 'Local Storage'), ('drive', 'Google Drive'), ('hybrid', 'Both Local and Drive')], default='local', max_length=20)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_url', models.URLField(blank=True, null=True)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded to Drive'), ('local', 'Local Only'), ('failed', 'Upload Failed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('location', models.CharField(default='Office', max_length=100)),
                ('reference', models.CharField(default='AUTO', max_length=100)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easydocs.doctype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Document',
                'verbose_name_plural': 'Office Documents',
            },
        ),
        migrations.CreateModel(
            name='DriveOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('access_token_encrypted', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_oauth_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], max_length=32)),
                ('receipt_no', models.CharField(blank=True, max_length=64)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LegalOfficePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('subservices', models.ManyToManyField(related_name='legalofficepayouts', to='easydocs.clientsubservice')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('reason', models.CharField(max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('send_status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easydocs.client')),
                ('client_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='easydocs.clientservice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('overridden_total_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='easydocs.clientservice')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='easydocs.service'),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False, unique=True)),
                ('company_name', models.CharField(default='SMARTSURVEYOR', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('tagline', models.CharField(blank=True, default='Thank you for letting us serve you!', max_length=255)),
                ('stamp_signature', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_drive_enabled', models.BooleanField(default=False)),
                ('google_drive_root_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_drive_service_account_key_encrypted', models.TextField(blank=True, null=True)),
                ('google_drive_service_account_email', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_auto_folder_creation', models.BooleanField(default=True)),
                ('drive_file_naming_pattern', models.CharField(default='{client_id}/{year}/{month}/{filename}', help_text='Available variables: {client_id}, {year}, {month}, {day}, {filename}', max_length=500)),
                ('drive_config_status', models.CharField(choices=[('not_configured', 'Not Configured'), ('configured', 'Configured'), ('testing', 'Testing'), ('error', 'Error')], default='not_configured', max_length=20)),
                ('drive_last_test_status', models.TextField(blank=True, null=True)),
                ('drive_last_test_at', models.DateTimeField(blank=True, null=True)),
                ('drive_config_updated_at', models.DateTimeField(auto_now=True)),
                ('drive_config_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TitleDeedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_by', models.CharField(help_text='Name of the person who picked the title deed', max_length=100)),
                ('id_number', models.CharField(blank=True, help_text='ID number of collector', max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_deed_collection', to='easydocs.clientservice')),
                ('submitted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('service_step', 'Service Process Step Payment'), ('sub_service', 'Sub-service Payment')], default='payment_step', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='easydocs.clientservice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='easydocs.payment')),
                ('service_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easydocs.clientserviceprocess')),
                ('sub_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easydocs.clientsubservice')),
            ],
            options={
                'indexes': [models.Index(fields=['reason'], name='easydocs_pa_reason_b74f2a_idx'), models.Index(fields=['created_at'], name='easydocs_pa_created_274ff3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(fields=('service', 'step_order'), name='unique_step_per_service'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['client', 'status'], name='easydocs_cl_client__10c73d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['service', 'status'], name='easydocs_cl_service_301198_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['requested_at'], name='easydocs_cl_request_9484d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientservice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('client', 'service', 'land_description'), name='unique_active_service_per_land'),
        ),
    ]
