# Generated by Django 5.2 on 2025-09-27 11:32

import apps.EasyDocs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdoc',
            name='doc_file',
            field=models.FileField(storage='apps.EasyDocs.files.storage_backends.UnifiedStorage', upload_to='documents/', validators=[apps.EasyDocs.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(storage='apps.EasyDocs.files.storage_backends.UnifiedStorage', upload_to='documents/', validators=[apps.EasyDocs.models.validate_file_size]),
        ),
    ]
