# Generated by Django 5.2 on 2025-05-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
        migrations.RemoveConstraint(
            model_name='clientservice',
            name='unique_active_service_per_land_v2',
        ),
        migrations.RemoveConstraint(
            model_name='process',
            name='unique_step_per_service_v2',
        ),
        migrations.AddConstraint(
            model_name='clientservice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('client', 'service', 'land_description'), name='unique_active_service_per_land_v2'),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(fields=('service', 'step_order'), name='unique_step_per_service_v2'),
        ),
    ]
