# Generated by Django 5.2 on 2025-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDocs', '0002_titledeedcollection_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titledeedcollection',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('collected', 'Title Deed Collected')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientserviceprocess',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('collected', 'Title Deed Collected')], default='pending', max_length=20),
        ),
    ]
