# Generated by Django 5.2 on 2025-09-27 11:40

import apps.EasyDocs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0002_alter_clientdoc_doc_file_alter_document_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdoc',
            name='doc_file',
            field=models.FileField(upload_to='documents/', validators=[apps.EasyDocs.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(upload_to='documents/', validators=[apps.EasyDocs.models.validate_file_size]),
        ),
    ]
