# Generated by Django 5.2 on 2025-09-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0003_alter_clientdoc_doc_file_alter_document_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdoc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('local', 'Local Only'), ('failed', 'Upload Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('local', 'Local Only'), ('failed', 'Upload Failed')], default='pending', max_length=20),
        ),
    ]
