# Generated by Django 5.2 on 2025-05-05 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0003_remove_clientservice_unique_active_service_per_land_v2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='full_total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Denormalized total for fast reads', max_digits=12),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='overridden_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['client', 'status'], name='easydocs_cl_client__10c73d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['service', 'status'], name='easydocs_cl_service_301198_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['requested_at'], name='easydocs_cl_request_9484d7_idx'),
        ),
    ]
