# Generated by Django 5.2 on 2025-05-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0004_clientservice_full_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_title_collection',
            field=models.BooleanField(default=False, help_text='If true, after the final process we show Confirm & Collect buttons; otherwise just Complete'),
        ),
    ]
