# Generated by Django 5.2 on 2025-04-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDocs', '0004_clientdoc_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='process',
        ),
        migrations.AddField(
            model_name='clientserviceprocess',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
