# Generated by Django 5.2 on 2025-09-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0004_alter_clientdoc_status_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_oauth_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_oauth_client_secret_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
