# Generated by Django 5.2 on 2025-05-09 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0005_service_requires_title_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subservice',
            name='is_paid_to_legal_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subservice',
            name='paid_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(choices=[('Legal', 'Legal')], default='Legal', max_length=20),
        ),
        migrations.CreateModel(
            name='LegalOfficePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('subservices', models.ManyToManyField(to='easydocs.subservice')),
            ],
        ),
    ]
