# Generated by Django 5.2 on 2025-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0005_sitesettings_google_oauth_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_oauth_redirect_uris',
            field=models.TextField(blank=True, default='', help_text='Allowed OAuth redirect URIs (one per line or comma-separated). Example: http://localhost:8080/drive/oauth/callback/'),
        ),
    ]
