# Generated by Django 5.2 on 2025-04-10 14:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDocs', '0006_subservice_credit_paymenthistory_refund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubservice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
