# Generated by Django 5.2 on 2025-05-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0006_subservice_date_recorded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='is_paid_to_legal_office',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='paid_month',
        ),
        migrations.AddField(
            model_name='clientsubservice',
            name='is_paid_to_legal_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientsubservice',
            name='paid_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
