# Generated by Django 5.2 on 2025-05-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0007_remove_subservice_is_paid_to_legal_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalofficepayout',
            name='subservices',
            field=models.ManyToManyField(to='easydocs.clientsubservice'),
        ),
    ]
