# Generated by Django 5.2 on 2025-10-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0007_payment_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed'), ('drive_sync', 'Drive Sync'), ('drive_failed', 'Drive Sync Failed'), ('payment', 'Payment Made'), ('payment_failed', 'Payment Failed'), ('expense_recorded', 'Expense Recorded'), ('expense_failed', 'Expense Recording Failed'), ('document_accessed', 'Document Accessed'), ('document_modified', 'Document Modified'), ('login', 'User Login'), ('logout', 'User Logout'), ('data_export', 'Data Exported'), ('data_import', 'Data Imported'), ('config_change', 'Configuration Changed'), ('other', 'Other')], max_length=20),
        ),
    ]
