# Generated by Django 5.2 on 2025-10-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0008_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='department',
            field=models.CharField(choices=[('Legal', 'Legal'), ('Other', 'Other')], default='Legal', max_length=20),
        ),
    ]
