# Generated by Django 5.2 on 2025-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0009_alter_subservice_department_alter_subservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalofficepayout',
            name='subservices',
            field=models.ManyToManyField(related_name='legalofficepayouts', to='easydocs.clientsubservice'),
        ),
    ]
