# Generated by Django 5.2 on 2025-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0009_alter_subservice_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveoauthtoken',
            name='needs_reauth',
            field=models.BooleanField(default=False),
        ),
    ]
