# Generated by Django 5.2 on 2025-10-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0010_driveoauthtoken_needs_reauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='applied_to_subservice',
            field=models.ForeignKey(blank=True, help_text='If set, apply this payment directly to the chosen client subservice', null=True, on_delete=django.db.models.deletion.PROTECT, to='easydocs.clientsubservice'),
        ),
    ]
