# Generated by Django 5.2 on 2025-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0010_alter_legalofficepayout_subservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubservice',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
