# Generated by Django 5.2 on 2025-05-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0011_clientsubservice_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='dispatch_message',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateTimeField()),
                ('dispatch_message', models.TextField(blank=True, null=True)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easydocs.clientservice')),
            ],
        ),
    ]
