# Generated by Django 5.2 on 2025-11-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to redirect when the user clicks the notification.', max_length=500, null=True),
        ),
    ]
