# Generated by Django 5.2 on 2025-05-14 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0012_remove_service_dispatch_message_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='handled_by',
            field=models.ForeignKey(blank=True, help_text='Who marked this booking as handled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easydocs.booking')),
                ('surveyor', models.ForeignKey(limit_choices_to={'groups__name': 'Surveyor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assigned_at'],
                'unique_together': {('booking', 'surveyor')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='surveyors',
            field=models.ManyToManyField(help_text='Which surveyors were allocated', limit_choices_to={'groups__name': 'Surveyor'}, related_name='assigned_bookings', through='easydocs.BookingAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
