# Generated by Django 5.2 on 2025-11-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0013_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Client profile picture (optional)', null=True, upload_to='clients/avatars/'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
