# Generated by Django 5.2 on 2025-11-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0014_client_profile_pic_delete_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
    ]
