# Generated by Django 5.2 on 2025-05-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0016_remove_client_collected_at_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_booking', to='easydocs.clientservice'),
        ),
    ]
