# Generated by Django 5.2 on 2025-05-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0017_alter_booking_client_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ground_booking', to='easydocs.clientservice'),
        ),
    ]
