# Generated by Django 5.2 on 2025-05-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0020_alter_booking_client_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdoc',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
