# Generated by Django 5.2 on 2025-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0022_scheduledtask_delete_recurringbroadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
