# Generated by Django 5.2 on 2025-05-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0023_clientservice_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
