# Generated by Django 5.2 on 2025-08-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0024_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='SMARTSURVEYOR', help_text='Company name for the receipt header', max_length=200),
        ),
    ]
