# Generated by Django 5.2 on 2025-12-20 19:18

import apps.EasyDocs.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0024_alter_client_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed'), ('drive_sync', 'Drive Sync'), ('drive_failed', 'Drive Sync Failed'), ('payment', 'Payment Made'), ('payment_failed', 'Payment Failed'), ('expense_recorded', 'Expense Recorded'), ('expense_failed', 'Expense Recording Failed'), ('document_accessed', 'Document Accessed'), ('document_modified', 'Document Modified'), ('login', 'User Login'), ('logout', 'User Logout'), ('data_export', 'Data Exported'), ('data_import', 'Data Imported'), ('config_change', 'Configuration Changed'), ('other', 'Other')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriveOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('access_token_encrypted', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needs_reauth', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clientdoc',
            options={'verbose_name': 'Client Document', 'verbose_name_plural': 'Client Documents'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Office Document', 'verbose_name_plural': 'Office Documents'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='easydocs_do_doc_nam_916037_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='easydocs_do_locatio_fa8161_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='easydocs_do_uploade_65a740_idx',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='phone',
            new_name='company_phone',
        ),
        migrations.RemoveField(
            model_name='clientdoc',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='mime_type',
        ),
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Client profile picture (optional)', null=True, upload_to='clients/avatars/'),
        ),
        migrations.AddField(
            model_name='clientdoc',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientdoc',
            name='drive_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdoc',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdoc',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clientdoc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('local', 'Local Only'), ('failed', 'Upload Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='clientdoc',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Local Storage'), ('drive', 'Google Drive'), ('hybrid', 'Both Local and Drive')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='clientsubservice',
            name='institution_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientsubservice',
            name='overridden_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_file',
            field=models.FileField(default=1, upload_to='documents/', validators=[apps.EasyDocs.models.validate_file_size]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='drive_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('local', 'Local Only'), ('failed', 'Upload Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Local Storage'), ('drive', 'Google Drive'), ('hybrid', 'Both Local and Drive')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='applied_to_subservice',
            field=models.ForeignKey(blank=True, help_text='If set, apply this payment directly to the chosen client subservice', null=True, on_delete=django.db.models.deletion.PROTECT, to='easydocs.clientsubservice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='institution_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='overridden_total_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who received the payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='drive_auto_folder_creation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='drive_config_status',
            field=models.CharField(choices=[('not_configured', 'Not Configured'), ('configured', 'Configured'), ('testing', 'Testing'), ('error', 'Error')], default='not_configured', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='drive_config_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='drive_config_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='drive_file_naming_pattern',
            field=models.CharField(default='{client_id}/{year}/{month}/{filename}', help_text='Available variables: {client_id}, {year}, {month}, {day}, {filename}', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='drive_last_test_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='drive_last_test_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_drive_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_drive_root_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_drive_service_account_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_drive_service_account_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_oauth_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_oauth_client_secret_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_oauth_redirect_uris',
            field=models.TextField(blank=True, default='', help_text='Allowed OAuth redirect URIs (one per line or comma-separated). Example: http://localhost:8080/drive/oauth/callback/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='easydocs.clientservice'),
        ),
        migrations.AlterField(
            model_name='clientdoc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='easydocs.client'),
        ),
        migrations.AlterField(
            model_name='clientdoc',
            name='doc_file',
            field=models.FileField(upload_to='documents/', validators=[apps.EasyDocs.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='clientdoc',
            name='doc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientdoc',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easydocs.doctype'),
        ),
        migrations.AlterField(
            model_name='clientdoc',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientsubservice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easydocs.doctype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='location',
            field=models.CharField(default='Office', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='reference',
            field=models.CharField(default='AUTO', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='SMARTSURVEYOR', max_length=200),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='department',
            field=models.CharField(choices=[('Legal', 'Legal'), ('Other', 'Other')], default='Legal', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driveoauthtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_oauth_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
