# Generated by Django 5.2 on 2025-12-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0025_auditlog_driveoauthtoken_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='is_company_copy',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='recipient_type',
            field=models.CharField(choices=[('client', 'Client'), ('employee', 'Employee'), ('company', 'Company')], default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_employee_email',
            field=models.BooleanField(default=False, help_text='If enabled, employees will also receive bulk email messages'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_employee_sms',
            field=models.BooleanField(default=False, help_text='If enabled, employees will also receive bulk SMS messages'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employee_sms_roles',
            field=models.JSONField(blank=True, default=list, help_text="Roles allowed to receive SMS e.g. ['Admin', 'Surveyor']"),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easydocs.client'),
        ),
        migrations.AddConstraint(
            model_name='messagelog',
            constraint=models.UniqueConstraint(condition=models.Q(('is_company_copy', True)), fields=('reason', 'is_company_copy'), name='unique_company_copy_per_reason'),
        ),
    ]
