# Generated by Django 5.2 on 2025-08-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0026_knowledgeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubservice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='clientsubservice',
            index=models.Index(fields=['is_active'], name='easydocs_cl_is_acti_c90be4_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubservice',
            index=models.Index(fields=['added_on'], name='easydocs_cl_added_o_3c03eb_idx'),
        ),
    ]
