# Generated by Django 5.2 on 2025-12-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0026_messagelog_is_company_copy_messagelog_recipient_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['delivery_status', 'timestamp'], name='msglog_delivery_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(condition=models.Q(('delivery_status', 'pending'), ('message_id__isnull', False)), fields=['timestamp'], name='msglog_pending_msg_id_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['-timestamp'], name='msglog_time_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['send_status'], name='msglog_send_status_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['message_id'], name='msglog_message_id_idx'),
        ),
    ]
