# Generated by Django 5.2 on 2025-12-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0027_scheduledtask_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
