# Generated by Django 5.2 on 2026-03-10 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('easydocs', '0028_scheduledtask_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientserviceprocess',
            name='completed_at_onboarding',
            field=models.BooleanField(default=False, help_text='True if this process was marked complete during client onboarding'),
        ),
        migrations.AddField(
            model_name='clientserviceprocess',
            name='onboarding_marked_at',
            field=models.DateTimeField(blank=True, help_text='When this process was marked complete during onboarding', null=True),
        ),
        migrations.AddField(
            model_name='clientserviceprocess',
            name='onboarding_marked_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this process as complete during onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process',
            name='notification_enabled',
            field=models.BooleanField(default=True, help_text='Global setting: enable automated notifications when this process completes'),
        ),
        migrations.AddField(
            model_name='service',
            name='expected_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Default expected duration in days for this service', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('title', 'Title Deed Service'), ('ground', 'Ground Service'), ('others', 'Other Services')], default='title', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reassigned', 'Reassigned')], default='pending', help_text='Current handoff status', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the employee accepted the document', null=True)),
                ('max_acceptance_time', models.DateTimeField(help_text='Maximum time for acceptance (assigned_at + 1 day)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the handoff')),
                ('assigned_by', models.ForeignKey(help_text='User who assigned the document', on_delete=django.db.models.deletion.CASCADE, related_name='created_document_handoffs', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='Employee to whom the document is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='received_document_handoffs', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, help_text='Client (if this is a ClientDoc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_handoffs', to='easydocs.client')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHandoffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reassigned', 'Reassigned')], help_text='Action taken', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the action')),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_handoff_actions', to=settings.AUTH_USER_MODEL)),
                ('handoff', models.ForeignKey(help_text='The handoff this log entry is for', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='easydocs.documenthandoff')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reassigned', 'Reassigned')], help_text='Action taken', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task_progress_at_reassignment', models.TextField(blank=True, help_text='JSON or text describing the task state at reassignment')),
                ('reason', models.TextField(blank=True, help_text='Reason for assignment/reassignment/decline')),
                ('assigned_by', models.ForeignKey(help_text='User who made the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('assigned_employee', models.ForeignKey(blank=True, help_text='Employee who received this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_assignments', to=settings.AUTH_USER_MODEL)),
                ('client_service', models.ForeignKey(help_text='The service that was assigned/reassigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='easydocs.clientservice')),
                ('previous_employee', models.ForeignKey(blank=True, help_text='Previous employee (for reassignments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDeadlineExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_deadline', models.DateTimeField(help_text='Previous deadline')),
                ('new_deadline', models.DateTimeField(help_text='New deadline after extension')),
                ('extended_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Reason for deadline extension')),
                ('client_service', models.ForeignKey(help_text='Service whose deadline was extended', on_delete=django.db.models.deletion.CASCADE, related_name='deadline_extensions', to='easydocs.clientservice')),
                ('extended_by', models.ForeignKey(help_text='User who extended the deadline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline_extensions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-extended_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documenthandoff',
            index=models.Index(fields=['assigned_to', 'status', '-assigned_at'], name='easydocs_do_assigne_8bcbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='documenthandoff',
            index=models.Index(fields=['client', '-assigned_at'], name='easydocs_do_client__b2f941_idx'),
        ),
        migrations.AddIndex(
            model_name='documenthandofflog',
            index=models.Index(fields=['handoff', '-timestamp'], name='easydocs_do_handoff_8fd865_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceassignmentlog',
            index=models.Index(fields=['client_service', '-timestamp'], name='easydocs_se_client__f30d31_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceassignmentlog',
            index=models.Index(fields=['assigned_employee', '-timestamp'], name='easydocs_se_assigne_3a0fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeadlineextension',
            index=models.Index(fields=['client_service', '-extended_at'], name='easydocs_se_client__18a1ee_idx'),
        ),
    ]
