# Generated by Django 5.2 on 2026-03-10 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0029_clientserviceprocess_completed_at_onboarding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, help_text='Employee assigned to this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='assignment_status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('pending_acceptance', 'Pending Acceptance'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reassigned', 'Reassigned')], default='unassigned', help_text='Current assignment status', max_length=20),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Calculated deadline based on assignment + duration', null=True),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='deadline_extended',
            field=models.BooleanField(default=False, help_text='True if deadline has been extended'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='expected_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Override service default expected duration', null=True),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='original_deadline',
            field=models.DateTimeField(blank=True, help_text='Original deadline before any extensions', null=True),
        ),
    ]
