# Generated by Django 5.2 on 2026-03-10 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0030_clientservice_assigned_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, help_text='Employee assigned to this task (for reminders)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='client_service',
            field=models.ForeignKey(blank=True, help_text='Related client service (for reminders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='easydocs.clientservice'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or context for the task'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('scheduled_sms', 'Scheduled SMS'), ('notification', 'Notification'), ('other', 'Other')], db_index=True, default='other', help_text='Type of scheduled task', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['task_type', 'status', 'scheduled_time'], name='easydocs_sc_task_ty_4dbf44_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['assigned_employee', 'status', 'scheduled_time'], name='easydocs_sc_assigne_ea48c7_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['client_service', 'status'], name='easydocs_sc_client__d4fc4e_idx'),
        ),
    ]
