# Generated by Django 5.2 on 2026-03-10 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0031_scheduledtask_assigned_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('reversal', 'Full Reversal'), ('partial', 'Partial Adjustment')], default='reversal', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive claw-back amount (posted as Cash OUT in cashbook)', max_digits=10)),
                ('reason', models.TextField(help_text='Mandatory audit reason for this adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Staff user who authorised this adjustment', on_delete=django.db.models.deletion.PROTECT, related_name='payment_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('original_payment', models.ForeignKey(help_text='The original payment being reversed or adjusted', on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='easydocs.payment')),
            ],
            options={
                'verbose_name': 'Payment Adjustment',
                'verbose_name_plural': 'Payment Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
