# Generated by Django 5.2 on 2026-03-11 00:00

import django.utils.timezone
from django.db import migrations, models


def normalize_paymenthistory_reason(apps, schema_editor):
    PaymentHistory = apps.get_model('easydocs', 'PaymentHistory')
    PaymentHistory.objects.filter(reason='payment_step').update(reason='service_step')


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0032_payment_adjustment'),
    ]

    operations = [
        migrations.RunPython(normalize_paymenthistory_reason, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paymenthistory',
            name='reason',
            field=models.CharField(
                choices=[
                    ('service_step', 'Service Process Step Payment'),
                    ('sub_service', 'Sub-service Payment'),
                ],
                default='service_step',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
