# Generated by Django 5.2 on 2026-03-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0033_harden_financial_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServicePaymentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('reversal', 'Full Reversal'), ('partial', 'Partial Adjustment')], default='reversal', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive claw-back amount (posted as Cash OUT in cashbook)', max_digits=10)),
                ('reason', models.TextField(help_text='Mandatory audit reason for this adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_sub_service', models.ForeignKey(help_text='The client sub-service whose paid amount is being corrected', on_delete=django.db.models.deletion.PROTECT, related_name='payment_adjustments', to='easydocs.clientsubservice')),
                ('created_by', models.ForeignKey(help_text='Staff user who authorised this adjustment', on_delete=django.db.models.deletion.PROTECT, related_name='subservice_payment_adjustments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub-service Payment Adjustment',
                'verbose_name_plural': 'Sub-service Payment Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
