# Generated by Django 5.2 on 2026-03-13 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0036_alter_sitesettings_company_name_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientServiceProcessAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rows are retained for audit when reassigned')),
                ('acceptance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_reason', models.TextField(blank=True)),
                ('completion_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this process step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(help_text='User assigned to this process step', on_delete=django.db.models.deletion.CASCADE, related_name='process_assignments', to=settings.AUTH_USER_MODEL)),
                ('client_service_process', models.ForeignKey(help_text='Process step being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='easydocs.clientserviceprocess')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientServiceProcessAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('reassigned', 'Reassigned')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_assignment_logs', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='easydocs.clientserviceprocessassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientserviceprocessassignment',
            index=models.Index(fields=['client_service_process', 'is_active', 'acceptance_status'], name='cspa_process_active_accept_idx'),
        ),
        migrations.AddIndex(
            model_name='clientserviceprocessassignment',
            index=models.Index(fields=['assignee', 'is_active', 'acceptance_status', 'completion_status'], name='cspa_assignee_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientserviceprocessassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('client_service_process', 'assignee'), name='uniq_active_process_assignment_per_assignee'),
        ),
        migrations.AddIndex(
            model_name='clientserviceprocessassignmentlog',
            index=models.Index(fields=['assignment', '-created_at'], name='easydocs_cl_assignm_7eb13c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientserviceprocessassignmentlog',
            index=models.Index(fields=['action', '-created_at'], name='easydocs_cl_action_b04feb_idx'),
        ),
        migrations.AddIndex(
            model_name='clientserviceprocessassignmentlog',
            index=models.Index(fields=['acted_by', '-created_at'], name='easydocs_cl_acted_b_a778e6_idx'),
        ),
    ]
