# Generated by Django 5.2 on 2026-03-26 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydocs', '0039_sitesettings_assignment_toggles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('client_service', 'scheduled_date'), name='unique_booking_client_service_datetime'),
        ),
    ]
