# Generated by Django 5.2.8 on 2025-12-01 17:17

import apps.subdivision.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.CharField(max_length=20)),
                ('area', models.DecimalField(decimal_places=6, max_digits=12)),
                ('perimeter', models.DecimalField(decimal_places=6, max_digits=12)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_modified', models.BooleanField(default=False)),
                ('parcel_type', models.CharField(choices=[('lot', 'Building Lot'), ('road', 'Road/Access'), ('utility', 'Utility Easement'), ('green', 'Green Space'), ('common', 'Common Area')], default='lot', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['parcel_number'],
            },
        ),
        migrations.CreateModel(
            name='ParcelCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('y_coordinate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('order_index', models.IntegerField()),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='subdivision.parcel')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionProject',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinate_file', models.FileField(help_text='Upload coordinate file (CSV, TXT, or Excel)', upload_to=apps.subdivision.models.subdivision_upload_path)),
                ('status', models.CharField(choices=[('uploaded', 'File Uploaded'), ('processing', 'Processing Coordinates'), ('mapping', 'Coordinate Mapping'), ('configured', 'Form Configured'), ('subdivided', 'Auto-Subdivided'), ('adjusted', 'Manual Adjustments'), ('completed', 'Deliverables Generated')], default='uploaded', max_length=20)),
                ('coordinate_system', models.CharField(blank=True, max_length=50)),
                ('land_area', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parcels', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('parcel_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mixed', 'Mixed Use')], default='residential', max_length=20)),
                ('min_parcel_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_parcel_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('layout_pattern', models.CharField(choices=[('grid', 'Grid Pattern'), ('organic', 'Organic Layout'), ('radial', 'Radial Pattern'), ('custom', 'Custom Layout')], default='grid', max_length=20)),
                ('road_width', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('setback_distance', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('preserve_trees', models.BooleanField(default=False)),
                ('water_access', models.BooleanField(default=False)),
                ('slope_constraints', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_config', to='subdivision.subdivisionproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Project Created'), ('uploaded', 'File Uploaded'), ('processed', 'Coordinates Processed'), ('configured', 'Form Configured'), ('subdivided', 'Auto-Subdivision Complete'), ('modified', 'Manual Modifications'), ('report_generated', 'Report Generated'), ('completed', 'Project Completed')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='subdivision.subdivisionproject')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='parcel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='subdivision.subdivisionproject'),
        ),
        migrations.CreateModel(
            name='SubdivisionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('survey_plan', 'Survey Plan'), ('parcel_list', 'Parcel List'), ('area_schedule', 'Area Schedule'), ('coordinate_list', 'Coordinate List'), ('technical_report', 'Technical Report'), ('cad_drawing', 'CAD Drawing')], max_length=30)),
                ('file_path', models.FileField(upload_to=apps.subdivision.models.subdivision_upload_path)),
                ('file_format', models.CharField(max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='subdivision.subdivisionproject')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='parcel',
            unique_together={('project', 'parcel_number')},
        ),
        migrations.CreateModel(
            name='CoordinateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(max_length=50)),
                ('x_coordinate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('y_coordinate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('z_coordinate', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('point_type', models.CharField(default='boundary', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='subdivision.subdivisionproject')),
            ],
            options={
                'ordering': ['order_index', 'point_id'],
                'unique_together': {('project', 'point_id')},
            },
        ),
    ]
