# Generated by Django 5.2.8 on 2025-12-02 04:02

import apps.subdivision.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdivision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivisionform',
            name='layout_pattern',
        ),
        migrations.RemoveField(
            model_name='subdivisionform',
            name='max_parcel_area',
        ),
        migrations.RemoveField(
            model_name='subdivisionform',
            name='min_parcel_area',
        ),
        migrations.RemoveField(
            model_name='subdivisionform',
            name='num_parcels',
        ),
        migrations.RemoveField(
            model_name='subdivisionform',
            name='parcel_type',
        ),
        migrations.RemoveField(
            model_name='subdivisionform',
            name='road_width',
        ),
        migrations.RemoveField(
            model_name='subdivisionform',
            name='setback_distance',
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='custom_angle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom angle in degrees', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='fitting_strategy',
            field=models.CharField(choices=[('full_plots_only', 'Take Only Full Plots That Fit'), ('resize_equally', 'Resize All Plots Equally'), ('reduce_plot_size', 'Reduce Individual Plot Size'), ('mixed_approach', 'AI-Mixed Approach')], default='mixed_approach', max_length=20),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='internal_road_width',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Internal access road width', max_digits=5),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='orientation',
            field=models.CharField(choices=[('north', 'North-South Orientation'), ('east', 'East-West Orientation'), ('optimal', 'AI-Optimal Orientation'), ('custom', 'Custom Angle')], default='optimal', max_length=20),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='plot_count_mode',
            field=models.CharField(choices=[('specify_count', 'Specify Number of Plots'), ('auto_fit', 'Auto-fit Maximum Plots')], default='auto_fit', max_length=20),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='plot_length',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Plot length in meters (e.g., 100)', max_digits=8),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='plot_width',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Plot width in meters (e.g., 50)', max_digits=8),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='preserve_features',
            field=models.BooleanField(default=True, help_text='Preserve natural features when possible'),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='road_detection',
            field=models.BooleanField(default=True, help_text='Auto-detect existing roads'),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='road_setback_front',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Front setback from road (m)', max_digits=5),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='road_setback_rear',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Rear setback (m)', max_digits=5),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='road_setback_side',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Side setback (m)', max_digits=5),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='specified_plot_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='terrain_awareness',
            field=models.BooleanField(default=True, help_text='Consider terrain in subdivision'),
        ),
        migrations.AddField(
            model_name='subdivisionform',
            name='use_satellite_imagery',
            field=models.BooleanField(default=True, help_text='Use satellite data for terrain analysis'),
        ),
        migrations.AddField(
            model_name='subdivisionproject',
            name='ai_processing_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdivisionproject',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subdivisionproject',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subdivisionproject',
            name='detected_crs',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subdivisionproject',
            name='map_zoom_level',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='subdivisionproject',
            name='perimeter',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='subdivisionproject',
            name='road_detection_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdivisionproject',
            name='terrain_analysis_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subdivisionproject',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Parent Plot Uploaded'), ('mapped', 'Parcel Mapped & Analyzed'), ('inspected', 'Boundaries Inspected'), ('configured', 'Subdivision Parameters Set'), ('plotted', 'AI Auto-Subdivision Complete'), ('adjusted', 'Interactive Adjustments Made'), ('approved', 'Layout Approved'), ('completed', 'Final Outputs Generated'), ('archived', 'Project Archived')], default='uploaded', max_length=20),
        ),
        migrations.CreateModel(
            name='RoadNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(blank=True, max_length=100)),
                ('road_type', models.CharField(choices=[('existing_major', 'Existing Major Road'), ('existing_minor', 'Existing Minor Road'), ('proposed_main', 'Proposed Main Access'), ('proposed_internal', 'Proposed Internal Road'), ('service_road', 'Service/Utility Road')], max_length=20)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('surface_type', models.CharField(choices=[('paved', 'Paved'), ('gravel', 'Gravel'), ('dirt', 'Dirt/Earth'), ('proposed', 'Proposed Construction')], default='proposed', max_length=20)),
                ('start_x', models.DecimalField(decimal_places=6, max_digits=15)),
                ('start_y', models.DecimalField(decimal_places=6, max_digits=15)),
                ('end_x', models.DecimalField(decimal_places=6, max_digits=15)),
                ('end_y', models.DecimalField(decimal_places=6, max_digits=15)),
                ('is_public_access', models.BooleanField(default=True)),
                ('requires_easement', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='subdivision.subdivisionproject')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('actions_performed', models.JSONField(default=list)),
                ('changes_made', models.JSONField(default=dict)),
                ('processing_time', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('api_calls_made', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='subdivision.subdivisionproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubdivisionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('size_mismatch', 'Plot Size Mismatch'), ('count_mismatch', 'Plot Count Mismatch'), ('access_problem', 'Access/Road Issue'), ('terrain_constraint', 'Terrain Constraint'), ('setback_violation', 'Setback Violation'), ('geometry_conflict', 'Geometry Conflict'), ('regulation_issue', 'Regulation Compliance')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low - Advisory'), ('medium', 'Medium - Attention Required'), ('high', 'High - Must Resolve'), ('critical', 'Critical - Blocking')], max_length=10)),
                ('description', models.TextField()),
                ('affected_area', models.TextField(blank=True)),
                ('suggested_solutions', models.JSONField(blank=True, default=list)),
                ('auto_fix_available', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('deferred', 'Deferred')], default='open', max_length=15)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='subdivision.subdivisionproject')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='TerrainAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_elevation', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_elevation', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('avg_slope', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_slope', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_water_features', models.BooleanField(default=False)),
                ('drainage_direction', models.CharField(blank=True, max_length=20)),
                ('flood_risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=10)),
                ('vegetation_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_mature_trees', models.BooleanField(default=False)),
                ('has_buildings', models.BooleanField(default=False)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terrain_analysis', to='subdivision.subdivisionproject')),
            ],
        ),
        migrations.CreateModel(
            name='BeaconPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_id', models.CharField(max_length=20)),
                ('x_coordinate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('y_coordinate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('z_coordinate', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('beacon_type', models.CharField(choices=[('boundary', 'Boundary Beacon'), ('plot_corner', 'Plot Corner'), ('road_marker', 'Road Marker'), ('utility_point', 'Utility Point'), ('control_point', 'Control Point')], default='boundary', max_length=20)),
                ('is_existing', models.BooleanField(default=False)),
                ('requires_setting', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to='subdivision.subdivisionproject')),
            ],
            options={
                'ordering': ['beacon_id'],
                'unique_together': {('project', 'beacon_id')},
            },
        ),
        migrations.CreateModel(
            name='ClientDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_type', models.CharField(choices=[('mutation_map', 'Mutation Map (PDF)'), ('beacon_list', 'Beacon Coordinate List'), ('area_summary', 'Area Summary Report'), ('gis_export', 'GIS Data Export'), ('client_preview', 'Client Preview Package'), ('survey_report', 'Professional Survey Report'), ('cad_drawings', 'CAD/DWG Files')], max_length=20)),
                ('file_path', models.FileField(upload_to=apps.subdivision.models.subdivision_upload_path)),
                ('file_format', models.CharField(max_length=10)),
                ('file_size', models.IntegerField(default=0)),
                ('sent_to_client', models.BooleanField(default=False)),
                ('client_approved', models.BooleanField(default=False)),
                ('client_feedback', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.IntegerField(default=1)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completeness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='subdivision.subdivisionproject')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('project', 'deliverable_type', 'version_number')},
            },
        ),
    ]
