# Generated by Django 5.2 on 2026-01-03 09:15

import apps.notifications.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('auth_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.CharField(max_length=255)),
                ('storage_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('messaging_sender_id', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('vapid_key', models.CharField(max_length=255)),
                ('service_account_json', apps.notifications.fields.EncryptedTextField(help_text='Paste your firebase-service-account.json content here. It will be encrypted on save.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firebase Configuration',
                'verbose_name_plural': 'Firebase Configuration',
            },
        ),
        migrations.AddField(
            model_name='pendingpushnotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
