# Generated by Django 5.2 on 2025-11-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pendingpushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
