# Generated by Django 5.2 on 2026-01-03 09:26

import apps.notifications.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_firebaseconfig_pendingpushnotification_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseconfig',
            name='service_account_json',
            field=apps.notifications.fields.EncryptedTextField(blank=True, help_text='Paste your firebase-service-account.json content here. It will be encrypted on save.'),
        ),
    ]
